services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/projects:/app/src/projects

  frontend:
    build:
      context: ./nlp-data-ui
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./nlp-data-ui:/app
      - /app/node_modules